spring:
  application:
    name: RecipeManager

  datasource:
    url: jdbc:postgresql://localhost:5432/recipemanager
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      # For test
      ddl-auto: update